### PR TITLE
Tweaked admin panel style

### PR DESCRIPTION
**Pull request by scye09**
Made some small style changes on admin panel page, please verify if these are the changes that were requested. Also I committed using the --no-verify flag, not sure if that is a problem.

### CODE REVIEW

**Comment by crchong1** [comment]
@scye09 can you just run it without the --no-verify flag? I would ideally like to not use the --no-verify flag anymore

**Comment by scye09** [comment]
@crchong1 Hmm how would I do that? Does that mean I need to resolve the 375 problems that the linter found before I can proceed?

**Comment by crchong1** [comment]
@scye09 nah i think the --no-verify command only will not pass if it hits lint errors. The 375 problems are labeled as warnings, not errors. If there are any errors within those 375 problems, you will have to fix them. 
Our goal one day is to eliminate all the 375 problems, so if you want to fix a couple of them if you have time, you are welcome to do so!

**Review by crchong1 — APPROVED** [review]
everything looks good to me- just make sure there are no lint errors. If you want to fix more lint errors, you are welcome to do so :)

**Review by steffen12 — APPROVED** [review]
Looks good to me! Should we still have "save changes" and "Delete account"?

**Pull request merged**
