### PR TITLE
Validations

### PR DESCRIPTION
**Pull request by joeyszhao**
@MelindaCardenas @crchong1

### CODE REVIEW

**Comment by crchong1** [comment]
Everything looks good to me so far. Lemme know when u add the rest of the validations

**Comment by MelindaCardenas** [comment]
things look good to me too, cool regex work 👍 I was also wondering, for dates, is it required for people to use "-" between numerical values (eg: birth date 01-15-1998) or is it possible that a user would use "/" to separate numerical values?

**Comment by crchong1** [comment]
@MelindaCardenas basically we use a datepicker react component to get the date information for us, so we dont have to worry about people entering manual dates

**Comment by crchong1** [comment]
@joeyszhao once you add the username/password validations, just ping me on slack and we can merge

**Pull request merged**
