### PR TITLE
create card components

### PR DESCRIPTION
**Pull request by loafyyy**
I created the card components using Michelle's @mishyi  (?) design: https://www.figma.com/file/m0pQ7jz59b5D8K9ErwfCu2/Cards?node-id=0%3A1

I created a new page at /card to view the card designs. I'll delete the page before merging the PR into master.

The way I implemented the component is that you pass in the following props (I think most of them are self-explanatory but I added comments below):
```
interface Props {
  cardHeight: string,
  cardWidth: string,
  cardTitle: string,
  cardText: string,
  imageSrc: any, // you need to import the image and then pass in the object
  imageLoc: string, // left, right, or top -- which side image is aligned to
  imageSize: string, // if the image is aligned to the left or right, you define the width, if it's aligned to the top, you define the height
  renderButton: boolean,
  buttonText: string,
  buttonOnClick: () => void, // onClick function for the button
  renderAdditionalContent: () => any, // you can customize with additional HTML here (pass in a function that returns HTML)
}
```

One thing I couldn't implement/think is going to be hard to implement is expanding the card on hover.

Also, apparently adding default props is annoying for React with TypeScript... if anyone knows how to do it please let me know. It's a little annoying to pass in all the props including props that aren't used (e.g. button props if there is no button on the card).

Some screenshots:
image

image

image

image

image

### CODE REVIEW

**Comment by loafyyy** [comment]
A video demo:
[Uploading demo.mov.zip…]()

**Review by crchong1 — CHANGES_REQUESTED** [review]
Instead of passing heights and widths as a prop, maybe can we pass in an enum like CARD_SM or CARD_MD or something like that, and then we would have pre-rendered heights and widths? This makes it a bit easier for engineers to make standardized sized cards without looking up the card dimensions for small, md, and large.

**Comment by crchong1** [comment]
Also can you pull all the SCSS changes into its own file (call it card.scss or something) just to separate the card scss?

**Comment by loafyyy** [comment]
> Instead of passing heights and widths as a prop, maybe can we pass in an enum like CARD_SM or CARD_MD or something like that, and then we would have pre-rendered heights and widths? This makes it a bit easier for engineers to make standardized sized cards without looking up the card dimensions for small, md, and large.

Yeah, I can do that. I'll make it so that someone can use pre-defined dimensions or custom dimensions.

**Comment by loafyyy** [comment]
@crchong1 I addressed your comments (standardized card sizes, moving styling to separate .scss file)

**Review by crchong1 — APPROVED** [review]
looks great

**Pull request merged**
