### PR TITLE
Application Form: added button & page num logic

### PR DESCRIPTION
**Pull request by vanessa-hu**
#81 , #129 (still WIP)
- **broke up q's into pages!!** had to play around to get questions to maintain prev-recorded answers
    - MAX_Q_PER_PAGE set to 10, so there are 10 questions per page (**does that look okay?**)
    - Previous button not there when on first page; usually previous & continue buttons. on last page, there's submit instead of continue
    - I have "Continue" reset the scroll to the top of the page but not "Previous." **any thoughts on that?**
- **About Submission**
    - @leonna26 what should happen if I try submitting **when all the q's aren't answered?** like, what should the button look like if it's disabled, and if there should be an alert.
    - I think all q's have to be answered to hit 100% & allow submission, but should that be more flexible (for instance, a CheckBox q with one option, "mark this if you have insurance" would force you to have an answer)? should we even block submission at all based on the % filled?

- **Question Types**
    - Is the CheckBox type a question with just 1 box to check? That's what the code currently presents it as & not a multiselect from multiple answers (all example form q's seem to just have 1)
    - ListBox type seems to be multi-select but I can't find an example to check it on.

- **pdfApplication**: @crchong1 if it's a pdfApplication do I just get rid of multiple pages completely?

- update on merge conflict: maybe I just accidentally replaced uuid() with index? lol
appform

### CODE REVIEW

**Comment by crchong1** [comment]
i think that merge conflict- we should use uiud for keys in general, and not do some wizardry with indices. this initial draft looks really great though! i will let some of the other ppl comment though

**Comment by crchong1** [comment]
also @leonna26 what do you think about a next and previous button at the top of the application as well

**Comment by leonna26** [comment]
thanks for your work on this, Vanessa! 

- can the page 1 (when the instance has no previous button) be centered below the form? 
- re: your question, @scye09 do you think this would be an appropriate use case for adding a critical error banner at the top of the screen to alert users to respond to all questions? i think that would be my suggestion
- are we able to have required/not required fields translated from backend to front-end for the form? that can help determine when to allow/block submission

**Comment by vanessa-hu** [comment]
@leonna26 I don't think there's a required/optional field to the questions :( in this case, I can remove the check for now (better to be less strict than more?)
let me know about the scroll as well!

**Comment by scye09** [comment]
Awesome work @vanessa-hu !! It looks so much better 💯 

Thank you for breaking up the form into multiple pages - I think 10 questions per page is good, especially since some of our forms are super long. 

For the progress bar, does that mean that answering all of the questions on 1 page will fill the bar to 100%? Or do they still need to fill out the entire form to get the bar to 100%? I think the latter approach would be preferable. 
Since some questions (like checkboxes) are not required, I think it might be better if the progress bar only advance once an entire page is complete and the user has clicked "Continue" instead of incrementally advancing as the user completes questions one by one.

As for resetting the scroll, I think it would make sense to reset scroll to the top of the page for both "Previous" and "Continue" just for consistency's sake. 

As for validation when no questions have been answered, I think we could highlight all of the blank boxes in red when they click submit, like so - the text below the textbox should say somethingT like "This field cannot be left blank." instead: 
TextField (Error)
and also reset scroll to the top of the page. @leonna26 using inline validation might be more preferable to using a warning banner just for consistency, since they'll be seeing these types of errors if they left even a few questions blank. What do you think?

**Comment by vanessa-hu** [comment]
changed progress bar to be based on pages, reset scroll for every page change & on submit as well. 

appform2

**Comment by steffen12** [comment]
Hi Team! Thank you for working on this Vanessa! I was working on this and fixed the UUID issue. Additionally, I added a required field and also a matching field - where it matches with a database value defined already. We have something akin to a fieldNumLines variable which tells you how many lines a question takes up (it is different for radio buttons with many options vs a text box) if you want to use this to limit the number of lines per page (20 was what we thought might be good last summer). Thank you again for this, please be in touch personally since I also worked on this week

**Review by crchong1 — APPROVED** [review]

**Pull request merged**
