### PR TITLE
Refactor client dashboard cards

### LINKED ISSUE #234: Modify client dashboard cards to be responsive on mobile
Refer to the following figma link, [](https://www.figma.com/file/3Xf9AS2CPzYg6dUtyy046t/Client-Dashboard?node-id=70%3A870 )

We want to ensure that the client dashboard cards are responsive to resizing

### PR DESCRIPTION
**Pull request by gkang2018**
Closes #234 #233 

Added BaseCard to ClientDashboard which reflects the designs:  [](https://www.figma.com/file/3Xf9AS2CPzYg6dUtyy046t/Dashboard?node-id=70%3A870)

Screen Shot 2021-01-29 at 4 32 18 PM
Screen Shot 2021-01-29 at 4 32 27 PM
Screen Shot 2021-01-29 at 4 32 50 PM

### CODE REVIEW

**Review by MelindaCardenas — APPROVED** [review]
It looks good to me, great work, Gagan! :-)

**Review by crchong1 — APPROVED** [review]
I think this looks great- i'll talk to Anna and see if we can have better card images from our new design system. Other than that, do you think you could also add a comment on what objectFit is? especially is it a string? an image? etc

**Comment by gkang2018** [comment]
> I think this looks great- i'll talk to Anna and see if we can have better card images from our new design system. Other than that, do you think you could also add a comment on what objectFit is? especially is it a string? an image? etc

Sounds good! Let me know what Anna says. And do you mean adding a comment within the BaseCard component explaining what it is and what the potential values are?

**Comment by crchong1** [comment]
@gkang2018 i think this looks great - I would merge now and then we can make an additional PR to change the icons in the future.

**Pull request merged**
