### PR TITLE
Lint errors issue3

### LINKED ISSUE #101: fix lint issues pt 3
image

fix lint errors in these files

### PR DESCRIPTION
**Pull request by MelindaCardenas**
Closes #101 

most notable change I made is in the eslint file. I changed :
"no-unused-vars": "off",
"@typescript-eslint/no-unused-vars":1,
because it was marking some enum variables as unused even though they were being used in MyAccount. Just seems more specific/customized to typescript.

### CODE REVIEW

**Comment by crchong1** [comment]
are we sure we should turn off no unused variables? I think we should just remove any unused variables rather than changing the rule

**Comment by MelindaCardenas** [comment]
@crchong1 so the "typescript-eslint/no-unused-vars" does the same job as "no-unused-vars" except it seems better suited for typescript. The typescript eslint version still flags unused variables, just doesn't flag the enums as unused unlike the normal version of "no-unused-vars" which falsely flags all enum variables as unused. 

Link to [enum variables I'm talking about](https://github.com/keepid/keepid_client/pull/228/files#diff-a7c046f552fe740b99f9f6ce54e536e69effa5913e51d523d5bfa36bacd0bc4eR12-R23)  Link to [typescript-eslint](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-unused-vars.md#options)

**Comment by crchong1** [comment]
Ah I see that makes sense. Nice investigating then!

**Review by crchong1 — APPROVED** [review]

**Comment by MelindaCardenas** [comment]
i ended up not needing to change the package.json file bc i didn't use airbnb-typescript, so I reverted the commit.

**Pull request merged**
