### PR TITLE
use new card component

### PR DESCRIPTION
**Pull request by loafyyy**
The new card component I implemented is now being used in:
`/signup-branch`
Before
image
After (new card component)
image

`/our-team`
Before
image

After (new card component)
image

`/our-partners`
Before
image

After (new card component)
image

### CODE REVIEW

**Comment by crchong1** [comment]
looks great- i like the new styling.

**Comment by crchong1** [comment]
quick comment before merging- do you think you could add quick image alts? it will break the linter if you don't have image alts. Plus it is a good accessibility thing

**Review by crchong1 — APPROVED** [review]
see comments

**Comment by loafyyy** [comment]
I already added image alts (based on what was there previously), but some of the alts are just alt="..."

**Pull request merged**
