### PR TITLE
Fix 404 redirect from Log Out button & Find Organizations button

### PR DESCRIPTION
**Pull request by vanessa-hu**
From Issue #35 : fixed logOut() in App.tsx to fetch /home and not unreachable /logout (404)
Also on LoginPage.tsx, realized Find Organizations button went to 404 & fixed to attribute in <Link> to /find-organizations

### CODE REVIEW

**Comment by crchong1** [comment]
@vanessa-hu jw do you think you could remove the changes for accountSignup?
Also, for the logout change, I think that approach actually doesn't work. I'll explain.

So when we hit the logout button, several things have to happen. 
1. There is a state variable that is called Role- one of the states is LoggedOut
2. We also have to send a get request to the server at the endpoint https://server.keep.id/logout. This is because the server needs to delete something called a session. Basically, the server also keeps track of all users who are using the site, and can serve each user with custom content based on their credentials. Deleting the session means that we remove the cached users from the server. 
3. We have to then redirect the page to /home

The thing about the strange 404 error this: 
I think we need to swap steps 1 and 3. We should redirect to /home first, then invalidate the server session, and then change the loggedOut state. Right now, the 404 happens because I think we invalidate the session and switch to loggedOut state, but if we are on a page like /admin-panel, the react client will actually first check if the user is logged in. This is because we want users who are not logged in to be prevented from seeing the admin panel. 

Let me know if that makes sense

**Comment by vanessa-hu** [comment]
Ah, I see... I had trouble returning a Redirect and then executing steps, but I think I figured something out (I think the new commit showed up there too) [commit here](https://github.com/keepid/keepid_client/commit/91e6a26f820cd082a01a8b406ec88b1ca22df58b)

- logOut() sets additional boolean prop called justLoggedOut to true, then redirects to home. Route (path="/home") checks if prop is true then executes logOutFinish() (update Role.loggedOut & fetch /logout) --> so then should return <Home> since it's now loggedOut.

**Comment by crchong1** [comment]
@vanessa-hu hii what's the status on this PR?

**Comment by vanessa-hu** [comment]
> @vanessa-hu hii what's the status on this PR?

I think we discussed this bc I couldn't figure it out for a while and you mentioned asking someone else to try?

**Comment by crchong1** [comment]
@kofmangregory  do you wanna take a look at this? not sure what is going on either

**Pull request closed without merging**
